# https://mlflow.org

mlflow:
  _target_: lightning.pytorch.loggers.mlflow.MLFlowLogger
  # experiment_name: ""
  run_name: ${run_name}
  tracking_uri: ${paths.log_dir}/mlflow/mlruns # run `mlflow ui` command inside the `logs/mlflow/` dir to open the UI
  tags:
    model.name: ${model.name} 
    data.name: ${data.train.dataset_name}
  prefix: ""
  artifact_location: null
  # run_id: ""
